import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const escape = (value) => value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");

export function routeMatches(route, target) {
  const segments = route.split("/").filter(Boolean);
  const pattern = segments.map((segment) => {
    if (/^\[\[\.\.\..+\]\]$/.test(segment)) return "(?:/[^/]+)*";
    if (/^\[\.\.\..+\]$/.test(segment)) return "(?:/[^/]+)+";
    if (/^\[.+\]$/.test(segment)) return "/[^/]+";
    return "/" + escape(segment);
  }).join("");
  return new RegExp("^" + (pattern || "/") + "/?$").test(target);
}

function routeContext(node, source) {
  for (let parent = node.parent; parent; parent = parent.parent) {
    if (ts.isJsxAttribute(parent)) return /^(href|action)$/.test(parent.name.getText(source));
    if (ts.isPropertyAssignment(parent)) return /^(href|url|prefix|start_url|source|destination)$/.test(parent.name.getText(source).replace(/["']/g, ""));
    if (ts.isCallExpression(parent)) {
      const name = parent.expression.getText(source);
      return /^(redirect|permanentRedirect|revalidatePath|fetch)$/.test(name) ||
        /(?:^|\.)(router|location)\.(push|replace|assign)$/.test(name) ||
        name === "window.open" || name.endsWith(".addAll");
    }
    if (ts.isNewExpression(parent)) return parent.expression.getText(source) === "URL";
    if (ts.isBinaryExpression(parent) && parent.operatorToken.kind === ts.SyntaxKind.EqualsToken) {
      return /location\.(href|pathname)$/.test(parent.left.getText(source));
    }
  }
  return false;
}

export function scanSource(text, filename, routes, assets = new Set()) {
  const source = ts.createSourceFile(filename, text, ts.ScriptTarget.Latest, true,
    filename.endsWith("x") ? ts.ScriptKind.TSX : ts.ScriptKind.TS);
  const references = [];
  function visit(node) {
    let target;
    if (ts.isStringLiteral(node) || ts.isNoSubstitutionTemplateLiteral(node)) target = node.text;
    if (ts.isTemplateExpression(node)) {
      target = node.head.text + node.templateSpans.map((span) => "__dynamic__" + span.literal.text).join("");
    }
    if (target?.startsWith("/") && !target.startsWith("//") && routeContext(node, source)) {
      const pathname = target.split(/[?#]/)[0];
      const line = source.getLineAndCharacterOfPosition(node.getStart(source)).line + 1;
      references.push({ filename, line, target, valid: assets.has(pathname) || routes.some((route) => routeMatches(route, pathname)) });
    }
    ts.forEachChild(node, visit);
  }
  visit(source);
  return references;
}

function files(directory) {
  if (!fs.existsSync(directory)) return [];
  return fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const name = path.join(directory, entry.name);
    return entry.isDirectory() ? files(name) : [name];
  });
}

export function auditRoutes(root = process.cwd()) {
  const app = path.join(root, "src/app");
  const routes = files(app).filter((file) => /\/(page|route)\.[cm]?[jt]sx?$/.test(file)).map((file) => {
    const segments = path.relative(app, path.dirname(file)).split(path.sep)
      .filter((segment) => segment && !segment.startsWith("(") && !segment.startsWith("@"));
    return "/" + segments.join("/");
  });
  // Metadata routes are generated by Next.js rather than page/route files.
  for (const [name, target] of [["manifest", "/manifest.webmanifest"], ["robots", "/robots.txt"], ["sitemap", "/sitemap.xml"]]) {
    if (["ts", "js"].some((extension) => fs.existsSync(path.join(app, `${name}.${extension}`)))) routes.push(target);
  }
  const assets = new Set(files(path.join(root, "public")).map((file) => "/" + path.relative(path.join(root, "public"), file).split(path.sep).join("/")));
  const config = path.join(root, "next.config.ts");
  const configText = fs.existsSync(config) ? fs.readFileSync(config, "utf8") : "";
  // Register explicit aliases, while checking their destinations below.
  for (const match of configText.matchAll(/\bsource:\s*["']([^"']+)["']/g)) routes.push(match[1]);
  const sources = [...files(path.join(root, "src")), ...files(path.join(root, "public"))]
    .filter((file) => /\.[jt]sx?$/.test(file) && !file.endsWith(".d.ts"));
  if (configText) sources.push(config);
  const references = sources.flatMap((file) => scanSource(fs.readFileSync(file, "utf8"), path.relative(root, file), routes, assets));
  for (const file of files(path.join(root, "public")).filter((file) => /(?:manifest.*\.json|\.webmanifest)$/.test(file))) {
    const manifest = JSON.parse(fs.readFileSync(file, "utf8"));
    for (const target of [manifest.start_url, ...(manifest.shortcuts ?? []).map((shortcut) => shortcut.url)]) {
      if (target?.startsWith("/")) references.push({ filename: path.relative(root, file), line: 1, target,
        valid: routes.some((route) => routeMatches(route, target.split(/[?#]/)[0])) });
    }
  }
  return { routes, references, missing: references.filter((reference) => !reference.valid) };
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = auditRoutes();
  for (const entry of result.missing) console.error(`${entry.filename}:${entry.line}: destino inexistente ${entry.target}`);
  console.log(`Rutas: ${result.routes.length}; referencias comprobadas: ${result.references.length}; destinos inexistentes: ${result.missing.length}`);
  if (result.missing.length) process.exitCode = 1;
}
